### ISSUE TITLE
Error calling DocumentsCreate: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by naulacambra** [SignRequest/signrequest-csharp-client#3]
I'm trying to use this Nuget in a .Net Standard project.

This is my code

``` cs
// Configure API key authorization: Token
Configuration.Default.AddApiKey("Authorization", "MYTOKEN");
Configuration.Default.AddApiKeyPrefix("Authorization", "Token");
// Configure API key authorization: Base Path
Configuration.Default.BasePath = "https://cedec-api.signrequest.com/api/v1";

var apiInstance = new DocumentsApi();
var data = new Document
{
    FileFromUrl = "https://docs.google.com/document/d/1oI2R1SxfMNZXiz3jCQvorpoklF9xq_dCJnOpkI-zo80/edit?usp=sharing"
};

try
{
     Document result = apiInstance.DocumentsCreate(data);
     Debug.WriteLine(result);
}
catch (Exception e)
{
     Debug.Print("Exception when calling DocumentsApi.DocumentsCreate: " + e.Message);
}
```` 

Almost the same that you have in your example, but I'm receiving an error.

``` console
Error calling DocumentsCreate: Operation is not supported on this platform.
```

What I'm doing wrong?

BTW, I'm using a sandbox

Thank you

**Comment by michi88** [comment]
We're getting back to you asap.

**Comment by cjackson** [comment]
@naulacambra I think this might be an issue with RestSharp. Which version are you currently using?

**Comment by daniel-burghardt** [comment]
I'm having the same issue.
I was initially using version 106.6.9 of RestSharp. then tried downgrading to version 105.1.0 but I kept on getting the same error.

Any ideas of why the issue?
Btw, I'm running .NET Core 2.0

**Comment by daniel-burghardt** [comment]
@michi88 @cjackson

**Comment by cjackson** [comment]
@daniel-burghardt Sorry we didn't see this issue before. I'll be able to take a look at this early next week. It seems to be working for me on .NET Core 2.1, but I'll see if I can reproduce it using 2.0.

**Comment by cjackson** [comment]
I was able to reproduce the issue using .NET Core 2.0. I just pushed out a v3.0.0 release that addresses this issue as well as brings the package up-to-date with the latest additions to our API. The new version targets .NET Standard 1.3, so should play a lot nicer with .NET Core.
