### ISSUE TITLE
Signers Null in SignRequestQuickCreate 

### ISSUE THREAD

**Issue by Bmadd** [SignRequest/signrequest-csharp-client#5]
Hi,

I beleieve there is a bug when instatiating a new SignRequestQuickCreate:

var data = new SignRequestQuickCreate(); 

following the example code at : 
https://github.com/SignRequest/signrequest-csharp-client/blob/v2.0.0/docs/SignrequestQuickCreateApi.md#signrequestquickcreatecreate

The exeception is as follows:

SignRequestQuickCreate signers is a required property for SignRequestQuickCreate and cannot be null

Cheers

**Comment by weetrax** [comment]
Same issue as @Bmadd 

Not only on the SignRequestQuickCreate, also on var data = new SignRequest.Model.SignRequest()

"System.IO.InvalidDataException: 'signers is a required property for SignRequest and cannot be null'"


`var signrequestsApi = new SignrequestsApi();`
`var signrequestsData = new SignRequest.Model.SignRequest()`
`{`
    `Signers = new List<Signer>() { new Signer() {Email = "name.surname@sample.com" } },`
    `FromEmail = "mywebsite@sample.com",`
    `Document = sampleDocument`
`};`
` SignRequest.Model.SignRequest signResult = signrequestsApi.SignrequestsCreate(signrequestsData);`

**Comment by cjackson** [comment]
It looks like the issue is that the required properties need to be set when constructing the `SignRequest` object. If you do it this way, it should work:

```csharp
var signrequestsApi = new SignrequestsApi();
var signrequestsData = new SignRequest.Model.SignRequest(
    signers: new List<Signer>() { new Signer(email: "name.surname@sample.com") },
    fromEmail: "mywebsite@sample.com",
    document: sampleDocument
);
SignRequest.Model.SignRequest signResult = signrequestsApi.SignrequestsCreate(signrequestsData);
```

**Comment by weetrax** [comment]
> It looks like the issue is that the required properties need to be set when constructing the `SignRequest` object. If you do it this way, it should work:
> 
> ```cs
> var signrequestsApi = new SignrequestsApi();
> var signrequestsData = new SignRequest.Model.SignRequest(
>     signers: new List<Signer>() { new Signer(email: "name.surname@sample.com") },
>     fromEmail: "mywebsite@sample.com",
>     document: sampleDocument
> );
> SignRequest.Model.SignRequest signResult = signrequestsApi.SignrequestsCreate(signrequestsData);
> ```

This is the same way I do. 

I have downloaded the SignRequest Client API througt the NuGet Packages manager and target the .NET Framework 4.6.2 in my project.

**Comment by weetrax** [comment]
It work that way.

Thanks !

**Comment by cjackson** [comment]
Great, thanks!
